version: '3.1'
services:
  db:
    image: mysql
    restart: always
    container_name: dockerdb
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "3307:3306"
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_SECRET}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_SECRET}"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ~/mysql:/var/lib/mysql
    # networks:
    #   - snippetbox
  adminer:
    image: adminer
    restart: always
    ports:
      - 9001:8080
    # networks:
    #   - snippetbox
# networks:
#   snippetbox:
#     driver: bridge
